### ISSUE TITLE
Update Manifest to correct version

### ISSUE THREAD

**Issue by sroertgen** [skohub-io/skohub-reconcile#23]
As @awagner-mainz correctly pointed out the current SkoHub Reconcile version follows the current draft of the [Reconcile Spec](https://github.com/reconciliation-api/specs) and *not* version 0.2 like currently stated in the manifest.

According to Semantic Versioning this can be stated as `0.3-alpha` (see https://semver.org/#spec-item-9)

Therefore the manifest should be changed to that.

**Comment by awagner-mainz** [comment]
turns out semver.org says semantic versions MUST include a patch version number before the prerelease suffix. So, `0.3.0-alpha` would be correct. I wonder if patch versioning will ever make it to the spec, though...

Found out because the semver library I want to use in my client complains and won't work with versions without patch number. I now have very patchy code in the client to inject a patch number (".0") if there is none.

**Comment by sroertgen** [comment]
you are right. The spec is quite clear about that.
Will fix.

**Comment by sroertgen** [comment]
Fixed and will assign you as reviewer in the PR.

FYI: This lib looks more up to date: https://github.com/npm/node-semver and I'm now using it to validate the manifest version in tests
